### ISSUE TITLE
Installation fails on Mac

### ISSUE THREAD

**Issue by gmjonker** [proycon/python-frog#10]
```
[...]
In file included from frog_wrapper.cpp:552:
In file included from /usr/local/include/frog/FrogAPI.h:36:
In file included from /usr/local/include/timbl/TimblAPI.h:35:
In file included from /usr/local/include/timbl/Common.h:32:
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did
      you mean 'finite'?
[...]
```

See attached file for complete output.

[install-error.txt](https://github.com/proycon/python-frog/files/2915214/install-error.txt)

**Comment by proycon** [comment]
You ran this installation outside of LaMachine I understand? (considering it's Python 2.7), but the error seems the same as what you reported in in proycon/LaMachine#136, so there's probably a common cause (I just don't know what yet).

**Comment by gmjonker** [comment]
Hey, that's surprising. I ran it outside LaMachine indeed, but with my `lamachine3` virtualenv active. How can that be Python 2.7...?

**Comment by proycon** [comment]
If you're inside a LaMachine virtualenv it should indeed have been inside LaMachine for all intents and purposes and used python3...

**Comment by gmjonker** [comment]
Indeed, `python3 -m setup.py install` gives the same result

**Comment by proycon** [comment]
Is this still an issue? There have been new releases of python-frog and LaMachine in the meantime and I haven't had any further reports on this. Closing it for now.
