### ISSUE TITLE
Outdated icu version

### ISSUE THREAD

**Issue by cdfa** [proycon/python-frog#12]
(Moved from https://github.com/LanguageMachines/frog/issues/69)

I got the following error when trying `from frog import Frog, FrogOptions` after updating `icu ` to 64.1: `ImportError: libicuio.so.63: cannot open shared object file: No such file or directory`.

Installing [icu63](https://aur.archlinux.org/packages/icu63/) from the AUR (and updating it's `icu` source to resolve the missing ssl certificate). Fixed the problem.

Being able to run with the latest `icu` would be nice.

**Comment by proycon** [comment]
Did you recompile (by for example reinstalling from the AUR) both frog as well as python-frog *after* the icu upgrade? The update would invalidate any earlier binary versions unfortunately.

It should work fine with the latest icu and doesn't specifically demand version 63.

**Comment by cdfa** [comment]
Good point, but the build seems to fail with the new `icu`. I tried to recompile and first I go an error that was fixed after installing the `autoconf-archive` package, but that's another issue. Then i tried again and this is the last bit from the log:
```
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -DSYSCONF_PATH=\"/usr/share\" -std=c++11 -W -Wall -pedantic -g -O3  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fopenmp -I/usr/include/libxml2   -fopenmp-I/usr/include/libxml2  -I/usr/include/libxml2  -I/usr/include/libxml2    -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o frog Frog.o libfrog.la -lucto  -lfolia  -lmbt  -ltimbl  -lticcutils  -licuio -licui18n -licuuc -licudata  -lxml2   -lreadline
libtool: link: g++ -DSYSCONF_PATH=\"/usr/share\" -std=c++11 -W -Wall -pedantic -g -O3 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fopenmp -I/usr/include/libxml2 -fopenmp -I/usr/include/libxml2 -I/usr/include/libxml2 -I/usr/include/libxml2 -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -o .libs/frog Frog.o  ./.libs/libfrog.so -lucto -lfolia -lmbt -ltimbl -lticcutils -licuio -licui18n -licuuc -licudata -lxml2 -lreadline -fopenmp
/bin/ld: ./.libs/libfrog.so: undefined reference to `TiCC::UniFilter::filter(icu_64::UnicodeString const&)'
/bin/ld: ./.libs/libfrog.so: undefined reference to `TiCC::UnicodeToUTF8[abi:cxx11](icu_64::UnicodeString const&)'
/bin/ld: ./.libs/libfrog.so: undefined reference to `TiCC::filter_diacritics(icu_64::UnicodeString const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:708: frog] Error 1
make[2]: Leaving directory '/home/cdfa/.cache/yay/frog/src/frog-0.15/src'
make[1]: *** [Makefile:482: all-recursive] Error 1
make[1]: Leaving directory '/home/cdfa/.cache/yay/frog/src/frog-0.15'
make: *** [Makefile:391: all] Error 2
==> ERROR: A failure occurred in build().
Aborting...
Error making: frog
```

**Comment by proycon** [comment]
Right yes, sorry, my mistake: it does not just apply to frog but to more in the dependency chain. You'll probably have to reinstall the AUR packages ticcutils, libfolia and perhaps also ucto first.

**Comment by cdfa** [comment]
Ah, that's it. It works now. Thank you :)
