### ISSUE TITLE
Installation in Docker (Debian-Buster) fails on Cython Language Setting

### ISSUE THREAD

**Issue by tsaltena** [proycon/python-frog#15]
In our development environment we have been having some success with following the build steps as outlined in #6 . Since the libfrog-dev library is available for the upcoming release of debian-buster, we were hoping to speed up our Docker builds by including it.

However, after updating the dependencies to the relevant Buster releases, we get the following stacktrace:
```
Failed to build python-frog
Installing collected packages: python-frog
  Running setup.py install for python-frog: started
    Running setup.py install for python-frog: finished with status 'error'
    ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-defg937t/python-frog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tqy26wez/install-record.txt --single-version-externally-managed --compile:
    ERROR: /usr/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'pyrex_gdb'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    cythoning frog_wrapper.pyx to frog_wrapper.cpp
    /usr/lib/python3/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-defg937t/python-frog/frog_wrapper.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'frog' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/ -I/usr/include/libxml2 -I/usr/local/include/ -I/usr/include/python3.7m -c frog_wrapper.cpp -o build/temp.linux-x86_64-3.7/frog_wrapper.o --std=c++0x -D U_USING_ICU_NAMESPACE=1
    frog_wrapper.cpp: In function ‘int __pyx_pf_4frog_4Frog___init__(__pyx_obj_4frog_Frog*, __pyx_obj_4frog_FrogOptions*, PyObject*)’:
    frog_wrapper.cpp:3661:147: error: no matching function for call to ‘FrogAPI::FrogAPI(FrogOptions&, TiCC::Configuration&, TiCC::LogStream*, TiCC::LogStream*)’
       __pyx_v_self->capi = new FrogAPI(__pyx_v_options->capi, __pyx_v_self->configuration, (&__pyx_v_self->logstream), (&__pyx_v_self->debuglogstream));
                                                                                                                                                       ^
    In file included from frog_wrapper.cpp:640:
    /usr/include/frog/FrogAPI.h:98:3: note: candidate: ‘FrogAPI::FrogAPI(FrogOptions&, const TiCC::Configuration&, TiCC::LogStream*)’
       FrogAPI( FrogOptions&,
       ^~~~~~~
    /usr/include/frog/FrogAPI.h:98:3: note:   candidate expects 3 arguments, 4 provided
    /usr/include/frog/FrogAPI.h:96:7: note: candidate: ‘constexpr FrogAPI::FrogAPI(const FrogAPI&)’
     class FrogAPI {
           ^~~~~~~
    /usr/include/frog/FrogAPI.h:96:7: note:   candidate expects 1 argument, 4 provided
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-defg937t/python-frog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tqy26wez/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-defg937t/python-frog/
ERROR: Service 'app' failed to build: The command '/bin/sh -c pip3 install python-frog' returned a non-zero code: 1
```

It appears to be related to Cython opting for a python2 language setting - but I'm explicitly telling the entire stack to use Python3. Is this a setting inside of the python-frog library somewhere? Is anyone else running into this issue?

**Comment by tsaltena** [comment]
Tried to fiddle around a bit with the language settings, but adding in 
> #cython: language_level=3

at the start of frog_wrapper.pyx and string-casting the configuration gives the same error. Any idea's on what's happening here? Frrogdata is version 0.16-1.

**Comment by tsaltena** [comment]
Right, the solution was explicitly requiring 0.37 since 0.40 is meant (as is in the release notes) for a newer libfrog-dev version. We can now compile a debian:buster Docker with frog using these dependencies:

> 	RUN apt-get install -y libticcutils-dev=0.20-1 libfolia-dev uctodata=0.8-2 libucto-dev \ 
libtimbl-dev frogdata=0.16-1 mbt=3.4-1 libfrog-dev=0.15-1

**Comment by proycon** [comment]
Sorry for the delay in getting back to you, but great that you found the solution yourself already! It is indeed a matter of choosing an older python-frog. The frog packages in debian are by definition always a bit older than our latest release. For the very latest releases we recommend [LaMachine](https://proycon.github.io/LaMachine) instead.

**Comment by tsaltena** [comment]
No problem, should've taken a closer look at the release notes. I got confused by the version appearing to match with the frogdata version instead of the libfrog version. It is weird that the Installation Requirement for the Cython package setup.py (https://github.com/proycon/python-frog/blob/3de4e4ef8778976ef08002d6f3f370e054413b4d/setup.py#L55) doesn't warn or error out. Anyway, it's nice that libfrog is now accessible in Debian:Buster, saves a whole lot of compilation in the Dockers.
