### ISSUE TITLE
Hardcoded sys path for libtexttextcat hinders the usage on shared clusters

### ISSUE THREAD

**Issue by avapirev** [proycon/python-frog#23]
Hi,

On many, if not most, shared machines software is not installed in default Linux directories.
The code looks for a hard-coded OS path for "libexttextcat" in "frog_wrapper.pyx".

`if os.path.isdir("/usr/share/libexttextcat")`

If libexttextcat has been installed elsewhere then "python-frog" is useless.

It would be very helpful if instead that is simply a check if "libexttextcat" is in "LD_LIBRARY_PATH", e.g., something like:

`if 'libexttextcattt' in os.environ['LD_LIBRARY_PATH']:`

Serious computational linguistics workflows are currently way beyond the usage on personal laptops and deskstations.

Best.

**Comment by proycon** [comment]
I agree the hardcoding is not a good solution. It is currently only used to install the data (so even if it's missing you still have all Frog functionality except the language detection). 

Your suggested check wouldn't work in this case, but I just committed a fix that should.

**Comment by avapirev** [comment]
Hi,
Coming back to this after a long break.
My suggested fix actually does work. Tested on a shared HPC cluster with central software installation. It properly detects if libexttextcat library is loaded and present in the user environment.
My other point is that your current fix has not been propagated (it seems) in its corresponding pypi python-frog package. Not sure if here is the place to comment on this.
best regards,

**Comment by proycon** [comment]
Long delay in replying here too, sorry: It should be in the 0.6.6 release from May , which is on Pypi.
