### ISSUE TITLE
running python-frog on LaMachine

### ISSUE THREAD

**Issue by Poezedoez** [proycon/python-frog#3]
Hi there,
I was wondering if you could help me with an error I got trying to run frog on LaMachine. I am already able to run it manually in the VM command line like this: frog -file. However, since I want to run it on a large dataset, I need to frog one document at a time in a loop. I am trying to run my own frog.py on the VM that contains the example code, but I get the following error: 
![error](https://cloud.githubusercontent.com/assets/8011906/15087123/4c440b96-13e6-11e6-96c6-a22269ef3321.png)
Caused by example code:
![code](https://cloud.githubusercontent.com/assets/8011906/15087155/8e249e0e-13e6-11e6-8c24-6d141e2e4fa1.png)
Looks like the VM is not able to find the module at all, but I have no idea how it could.
Do you have any idea?

**Comment by proycon** [comment]
I suspect the problem is caused because you called your script `frog.py`. which `import frog` then tries to import instead of the actual Frog module. The `has no attribute Frog` error should never occur if it's the proper module, if anything goes wrong I'd expect a normal `ImportError` instead.

**Comment by Poezedoez** [comment]
That was actually it! I feel so silly now. 
Thank you for your quick response.
