### ISSUE TITLE
Error when trying to install python-frog

### ISSUE THREAD

**Issue by DStekel3** [proycon/python-frog#8]
Hi, I'm getting the following error when I try to install python-frog: 
`C:\Users\dst\Source\Repos\_WorkflowPatternFinder\WorkflowPatternFinder>pip install python-frog
Collecting python-frog
  Using cached https://files.pythonhosted.org/packages/3f/2f/cb11ee8f282c3f85d30ba64ecb1c4ce501e1cac8fd6bed671b7382847c9c/python-frog-0.3.7.tar.gz
Requirement already satisfied: Cython in c:\python34\lib\site-packages (from python-frog) (0.28.2)
botocore 1.9.11 has requirement python-dateutil<2.7.0,>=2.1, but you'll have python-dateutil 2.7.0 which is incompatible.
Installing collected packages: python-frog
  Running setup.py install for python-frog ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dst\\AppData\\Local\\Temp\\pip-install-ha1roqvg\\python-frog\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dst\AppData\Local\Temp\pip-record-vzin9j8h\install-record.txt --single-version-externally-managed --compile:
    c:\python34\lib\distutils\extension.py:132: UserWarning: Unknown Extension options: 'pyrex_gdb'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    cythoning frog_wrapper.pyx to frog_wrapper.cpp
    building 'frog' extension
    creating build
    creating build\temp.win-amd64-3.4
    creating build\temp.win-amd64-3.4\Release
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\x86_amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/ -I/usr/include/libxml2 -I/usr/local/include/ -Ic:\python34\include -Ic:\python34\include /Tpfrog_wrapper.cpp /Fobuild\temp.win-amd64-3.4\Release\frog_wrapper.obj --std=c++0x "-D U_USING_ICU_NAMESPACE=1"
    cl : Command line warning D9002 : ignoring unknown option '--std=c++0x'
    frog_wrapper.cpp
    c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\xlocale(323) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
    frog_wrapper.cpp(587) : fatal error C1083: Cannot open include file: 'libfolia/folia.h': No such file or directory
    error: command '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\x86_amd64\cl.exe"' failed with exit status 2`

Does anyone know what I can do to fix this?

**Comment by proycon** [comment]
You're compiling on Windows, Frog is not supported on Windows (or at least; not at all tested, you can give it a try but it will be a complex endeavour). Please look into our [LaMachine](https://proycon.github.io/lamachine) distribution instead, ``python-frog`` and all dependencies are included there (in a Linux environment, but you can run it as VM or in the Linux subsystem on windows)

**Comment by DStekel3** [comment]
Thanks for the fast response. Too bad that the python-frog is not supported on Windows :(
